//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shykment_international
{
    using System;
    using System.Collections.Generic;
    
    public partial class Arrivals
    {
        public int id { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<int> id_Airline { get; set; }
        public Nullable<int> id_City { get; set; }
        public Nullable<System.DateTime> Arrival { get; set; }
        public Nullable<int> ArrivalsHall { get; set; }
    
        public virtual Airlines Airlines { get; set; }
        public virtual Cities Cities { get; set; }
    }
}
